// Generated by CoffeeScript 1.4.0
(function() {

  QUnit.test("diag.delete_class", function(assert) {
    var actual, c, diag, expected;
    expected = 2;
    diag = new Diagram();
    c = new Class("hi world");
    diag.agregar_clase(new Class("Class1"));
    diag.agregar_clase(c);
    diag.agregar_clase(new Class("Class1"));
    diag.delete_class(c);
    actual = diag.get_clases().length;
    return assert.equal(actual, expected, "Passed!");
  });

  QUnit.test("diag.delete_by_name", function(assert) {
    var actual, c, diag, expected;
    expected = 2;
    diag = new Diagram();
    c = new Class("hi world");
    diag.agregar_clase(new Class("Class1"));
    diag.agregar_clase(c);
    diag.agregar_clase(new Class("Class2"));
    diag.delete_class_by_name("hi world");
    actual = diag.get_clases().length;
    return assert.equal(actual, expected, "Passed!");
  });

  QUnit.test("diag.delete_by_classid", function(assert) {
    var actual, c, c1, c2, classid, diag, expected, fact, graph;
    expected = 2;
    diag = new Diagram();
    fact = new UMLFactory();
    graph = new joint.dia.Graph();
    c1 = new Class("Class1");
    c = new Class("hi world");
    c2 = new Class("Class2");
    c1.create_joint(fact);
    c.create_joint(fact);
    c2.create_joint(fact);
    classid = c.get_classid();
    diag.agregar_clase(c1);
    diag.agregar_clase(c);
    diag.agregar_clase(c2);
    diag.delete_class_by_classid(classid);
    actual = diag.get_clases().length;
    return assert.equal(actual, expected, "Passed!");
  });

}).call(this);
