// Generated by CoffeeScript 1.4.0
(function() {

  QUnit.test("diag.to_json", function(assert) {
    var actual, diag, expected;
    expected = {
      classes: [
        {
          name: "hi world"
        }
      ],
      links: []
    };
    diag = new Diagram();
    diag.agregar_clase(new Class("hi world"));
    actual = diag.to_json();
    return assert.propEqual(actual, expected, "dia.to_json");
  });

  QUnit.test("diag.to_json with links", function(assert) {
    var actual, cell, diag, expected, link, person;
    expected = {
      classes: [
        {
          name: "Person"
        }, {
          name: "Cellphones"
        }
      ],
      links: [
        {
          classes: ["Person", "Cellphones"],
          multiplicity: ["1..1", "1..*"],
          name: "",
          type: "association"
        }
      ]
    };
    diag = new Diagram();
    person = new Class("Person");
    cell = new Class("Cellphones");
    diag.agregar_clase(person);
    diag.agregar_clase(cell);
    link = new Link([person, cell]);
    diag.agregar_link(link);
    actual = diag.to_json();
    return assert.propEqual(actual, expected, "dia.to_json");
  });

}).call(this);
