// Generated by CoffeeScript 1.10.0
(function() {
  QUnit.test("diag.to_json", function(assert) {
    var actual, diag, expected;
    expected = {
      classes: [
        {
          name: "hi world"
        }
      ],
      links: []
    };
    diag = new Diagrama();
    diag.agregar_clase(new Class("hi world"));
    actual = diag.to_json();
    return assert.equal(actual, expected, "Passed!");
  });

}).call(this);
