// Generated by CoffeeScript 1.10.0
(function() {
  QUnit.test("diag.to_json", function(assert) {
    var actual, diag, expected;
    expected = {
      classes: [
        {
          name: "hi world",
          attrs: [],
          methods: [],
          position: {
            x: 20,
            y: 20
          }
        }
      ],
      links: []
    };
    diag = new model.uml.UMLDiagram();
    diag.agregar_clase(new model.uml.Class("hi world"));
    actual = diag.to_json();
    return assert.propEqual(actual, expected, "dia.to_json");
  });

  QUnit.test("diag.to_json with links", function(assert) {
    var actual, cell, diag, expected, link, person;
    expected = {
      classes: [
        {
          name: "Person",
          attrs: [],
          methods: [],
          position: {
            x: 20,
            y: 20
          }
        }, {
          name: "Cellphones",
          attrs: [],
          methods: [],
          position: {
            x: 20,
            y: 20
          }
        }
      ],
      links: [
        {
          classes: ["Person", "Cellphones"],
          multiplicity: ["1..1", "1..*"],
          roles: [null, null],
          name: "role",
          type: "association"
        }
      ]
    };
    diag = new model.uml.UMLDiagram();
    person = new model.uml.Class("Person");
    cell = new model.uml.Class("Cellphones");
    diag.add_class(person);
    diag.add_class(cell);
    link = new model.uml.Link([person, cell], "role");
    link.set_mult(["1..1", "1..*"]);
    diag.agregar_link(link);
    actual = diag.to_json();
    return assert.propEqual(actual, expected, "dia.to_json");
  });

}).call(this);
