// Generated by CoffeeScript 1.10.0
(function() {
  QUnit.test("EERDiagram.to_json", function(assert) {
    var actual, c1, c2, diag, expected;
    expected = {
      classes: [
        {
          name: "PhoneCall",
          position: {
            x: 20,
            y: 20
          }
        }, {
          name: "Phone",
          position: {
            x: 20,
            y: 20
          }
        }
      ],
      attributes: [
        {
          name: "date",
          type: "normal"
        }, {
          name: "location",
          type: "normal"
        }
      ],
      links: [
        {
          name: "PhoneCalldate",
          classes: ["PhoneCall", "date"],
          type: "attribute"
        }, {
          name: "Phonelocation",
          classes: ["Phone", "location"],
          type: "attribute"
        }
      ]
    };
    diag = new model.eer.ERDiagram();
    c1 = new model.eer.Entity("PhoneCall");
    c2 = new model.eer.Entity("Phone");
    diag.add_entity(c1);
    diag.add_entity(c2);
    diag.add_attribute(new model.eer.LinkAttrToEntity(c1, 'date'));
    diag.add_attribute(new model.eer.LinkAttrToEntity(c2, 'location'));
    actual = diag.to_json();
    return assert.propEqual(actual, expected, "EERDiagram.to_json");
  });

}).call(this);
