// Generated by CoffeeScript 1.12.5
var Diagram, exports;

Diagram = (function() {
  function Diagram(graph) {
    this.graph = graph != null ? graph : null;
    this.factory = null;
  }

  Diagram.prototype.reset = function() {};

  Diagram.prototype.get_factory = function() {
    return this.factory;
  };

  Diagram.prototype.set_factory = function(factory) {
    this.factory = factory;
  };

  Diagram.prototype.update_view = function(class_id, paper) {};

  Diagram.prototype.find_class_by_name = function(name) {};

  Diagram.prototype.find_class_by_classid = function(classid) {};

  Diagram.prototype.find_attr_by_attrid = function(attrid) {};

  Diagram.prototype.get_graph = function() {
    return this.graph;
  };

  Diagram.prototype.set_graph = function(graph) {
    this.graph = graph;
  };

  Diagram.prototype.actualizar_graph = function() {};

  Diagram.prototype.to_json = function() {};

  Diagram.prototype.import_json = function(json) {};

  return Diagram;

})();

exports = exports != null ? exports : this;

exports.Diagram = Diagram;
