// Generated by CoffeeScript 1.12.5
(function() {
  var Product, exports;

  Product = (function() {
    function Product() {}

    return Product;

  })();

  exports = exports != null ? exports : this;

}).call(this);
