// Generated by CoffeeScript 1.12.5
var ServerConnection, exports;

ServerConnection = (function() {
  function ServerConnection(error_callback) {
    this.error_callback = error_callback;
    this.urlprefix = "";
  }

  ServerConnection.prototype.set_urlprefix = function(str) {
    return this.urlprefix = str;
  };

  ServerConnection.prototype.request_satisfiable = function(json, callback_function) {
    var postdata, url;
    postdata = "json=" + json;
    url = this.urlprefix + "api/querying/satisfiable.php";
    console.log("Requesting at " + url);
    return $.ajax({
      type: "POST",
      url: url,
      data: postdata,
      success: callback_function,
      error: this.error_callback
    });
  };

  ServerConnection.prototype.request_translation = function(json, format, callback_function) {
    var url;
    url = this.urlprefix + "api/translate/crowd.php";
    console.log("Requesting at " + url);
    return $.ajax({
      type: "POST",
      url: url,
      data: {
        "format": format,
        "json": json
      },
      success: callback_function,
      error: this.error_callback
    });
  };

  ServerConnection.prototype.request_metamodel_translation = function(json, callback_function) {
    var url;
    url = this.urlprefix + "api/translate/metamodel.php";
    console.log("Requesting at " + url);
    return $.ajax({
      type: "POST",
      url: url,
      data: {
        "json": json
      },
      success: callback_function,
      error: this.error_callback
    });
  };

  ServerConnection.prototype.request_meta2erd_translation = function(json, callback_function) {
    var url;
    url = this.urlprefix + "api/translate/metamodeltoerd.php";
    console.log("Requesting at " + url);
    return $.ajax({
      type: "POST",
      url: url,
      data: {
        "json": json
      },
      success: callback_function,
      error: this.error_callback
    });
  };

  ServerConnection.prototype.request_meta2orm_translation = function(json, callback_function) {
    var url;
    url = this.urlprefix + "api/translate/metamodeltoorm.php";
    console.log("Requesting at " + url);
    return $.ajax({
      type: "POST",
      url: url,
      data: {
        "json": json
      },
      success: callback_function,
      error: this.error_callback
    });
  };

  return ServerConnection;

})();

exports = exports != null ? exports : this;

exports.ServerConnection = ServerConnection;
