<?php 
/* 

   Copyright 2016 Giménez, Christian
   
   Author: Giménez, Christian   

   jsonanswer.php
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Wicom\Answers;

/**
   A reasoner answer summary.
*/
class Answer{

    protected $kb_satis = null;
    protected $satis_classes = [];
    protected $unsatis_classes = [];
    protected $suggestions = null;
    protected $reasoner = null;

    function __construct(){
        
    }

    
    /**
       The string generated by to_json() is like the following.
       
       @code{.json}
{ 
    "satisfiable": {
        "kb" : true,
        "classes" : ["name1", "name2"]
    },
    "unsatisfiable": {
	"classes" : ["name3", "name4"]
    },
    "suggestions" : {
	"links" : [
	    {"name" : "suggestion 1",
	     "classes": ["classname 1", "classname 2"]}
	]
    },
    "reasoner" : {
	"input" : "STRING WITH REASONER INPUT",
	"output" : "STRING WITH REASONER OUTPUT"
    }
}
    @endcode
    */    
    function to_json(){
        
    }
}
