// Generated by CoffeeScript 1.12.5
var ClassOptionsView, exports;

ClassOptionsView = Backbone.View.extend({
  initialize: function() {
    this.render();
    return this.$el.hide();
  },
  render: function() {
    var template;
    template = _.template($("#template_classoptions").html());
    return this.$el.html(template({
      classid: this.classid
    }));
  },
  events: {
    "click a#deleteclass_button": "delete_class",
    "click a#editclass_button": "edit_class"
  },
  set_classid: function(classid) {
    var viewpos;
    this.classid = classid;
    viewpos = graph.getCell(this.classid).findView(paper).getBBox();
    this.$el.css({
      top: viewpos.y,
      left: viewpos.x,
      position: 'absolute',
      'z-index': 1
    });
    return this.$el.show();
  },
  get_classid: function() {
    return this.classid;
  },
  delete_class: function(event) {
    gui.gui_instance.hide_options();
    return gui.gui_instance.delete_class(this.classid);
  },
  edit_class: function(event) {
    gui.gui_instance.hide_options();
    gui.gui_instance.set_editclass_classid(this.classid);
    return this.hide();
  },
  hide: function() {
    return this.$el.hide();
  }
});

exports = exports != null ? exports : this;

exports.ClassOptionsView = ClassOptionsView;
