// Generated by CoffeeScript 1.12.5
var CreateClassView, exports;

CreateClassView = Backbone.View.extend({
  initialize: function() {
    return this.render();
  },
  render: function() {
    var template;
    template = _.template($("#template_tools_navbar").html(), {});
    return this.$el.html(template);
  },
  events: {
    "click a#crearclase_button": "create_class",
    "click a#translate_button": "translate_owllink",
    "click a#insertowllink_button": "insert_owllink",
    "click a#resetall_button": "reset_all",
    "click a#importjson_open_dialog": "import_json",
    "click a#exportjson_open_dialog": "export_json",
    "click a#meta_erd_button": "meta_to_erd"
  },
  meta_to_erd: function(event) {
    console.log(event);
    return guiinst.to_erd();
  },
  create_class: function(event) {
    return guiinst.add_object_type({
      name: $("#crearclase_input").val()
    });
  },
  translate_owllink: function(event) {
    return guiinst.translate_owllink();
  },
  get_translation_format: function() {
    return $("#format_select")[0].value;
  },
  insert_owllink: function() {
    return guiinst.show_insert_owllink();
  },
  reset_all: function() {
    return guiinst.reset_all();
  },
  import_json: function() {
    return guiinst.show_import_json();
  },
  export_json: function() {
    return guiinst.show_export_json();
  }
});

exports = exports != null ? exports : this;

exports.CreateClassView = CreateClassView;
