// Generated by CoffeeScript 1.12.5
var EditClassView, exports;

EditClassView = Backbone.View.extend({
  initialize: function() {
    this.render();
    return this.$el.hide();
  },
  render: function() {
    var template;
    template = _.template($("#template_editclass").html());
    return this.$el.html(template({
      classid: this.classid
    }));
  },
  events: {
    "click a#editclass_button": "edit_class",
    "click a#close_button": "hide"
  },
  set_classid: function(classid) {
    var viewpos;
    this.classid = classid;
    viewpos = graph.getCell(this.classid).findView(paper).getBBox();
    this.$el.css({
      top: viewpos.y,
      left: viewpos.x,
      position: 'absolute',
      'z-index': 1
    });
    return this.$el.show();
  },
  get_classid: function() {
    return this.classid;
  },
  edit_class: function(event) {
    var name;
    name = $("#editclass_input").val();
    gui.gui_instance.edit_class_name(this.classid, name);
    return gui.gui_instance.hide_options();
  },
  hide: function() {
    return this.$el.hide();
  }
});

exports = exports != null ? exports : this;

exports.EditClassView = EditClassView;
