// Generated by CoffeeScript 1.12.5
var ErrorWidgetView, exports;

ErrorWidgetView = Backbone.View.extend({
  initialize: function() {
    this.render();
    return this.$el.find(".error-popup").popup();
  },
  render: function() {
    var template;
    template = _.template($("#template_errorwidget").html());
    return this.$el.html(template());
  },
  show: function(status, message) {
    $(".error-popup").popup("open");
    $("#errorstatus_text").html(status);
    $("#errormsg_text").html(message);
    return console.log(status + " - " + message);
  },
  events: {
    "click a#errorwidget_hide_btn": "hide"
  },
  hide: function() {
    return $(".error-popup").popup("close");
  }
});

exports = exports != null ? exports : this;

exports.ErrorWidgetView = ErrorWidgetView;
