// Generated by CoffeeScript 1.12.5
var ExportJSONView, exports;

ExportJSONView = Backbone.View.extend({
  initialize: function() {
    this.jsonstr = "";
    return this.render();
  },
  render: function() {
    var template;
    template = _.template($("#template_exportjson").html());
    this.$el.html(template({
      jsonstr: this.jsonstr
    }));
    return this.$el.enhanceWithin();
  },
  events: {
    "click a#exportjson_copybtn": "copy_jsonstr",
    "click a#exportjson_refreshbtn": "refresh"
  },
  copy_jsonstr: function() {
    console.log("Copying: " + this.jsonstr);
    return document.execCommand("copy", false, this.jsonstr);
  },
  refresh: function() {
    return guiinst.refresh_export_json();
  },
  set_jsonstr: function(jsonstr) {
    this.jsonstr = jsonstr;
    return this.render();
  }
});

exports = exports != null ? exports : this;

exports.ExportJSONView = ExportJSONView;
