// Generated by CoffeeScript 1.12.5
var ImportJSONView, exports;

ImportJSONView = Backbone.View.extend({
  initialize: function() {
    this.render();
    this.$el.find(".importjson-popup").popup();
    return $("#importjson_importbtn").on('click', this.do_import);
  },
  render: function() {
    var template;
    template = _.template($("#template_importjson").html());
    return this.$el.html(template());
  },
  show: function() {
    return $(".importjson-popup").popup("open");
  },
  events: {
    "click a#importjson_importbtn": "do_import"
  },
  do_import: function() {
    var jsonstr;
    console.log("Doing import now!");
    $(".importjson-popup").popup("close");
    jsonstr = $("#importjson_input").val();
    return guiinst.import_jsonstr(jsonstr);
  }
});

exports = exports != null ? exports : this;

exports.ImportJSONView = ImportJSONView;
