// Generated by CoffeeScript 1.12.5
var IsaOptionsView, exports;

IsaOptionsView = Backbone.View.extend({
  initialize: function() {
    this.render();
    return this.$el.hide();
  },
  render: function() {
    var template;
    template = _.template($("#template_isaoptions").html());
    return this.$el.html(template({
      classid: this.classid
    }));
  },
  events: {
    'click a#isa_button': 'new_isa'
  },
  new_isa: function() {
    var covering, disjoint;
    disjoint = $("#chk-disjoint").prop("checked");
    covering = $("#chk-covering").prop("checked");
    return guiinst.set_isa_state(this.classid, disjoint, covering);
  },
  set_classid: function(classid) {
    var viewpos;
    this.classid = classid;
    viewpos = graph.getCell(this.classid).findView(paper).getBBox();
    this.$el.css({
      top: viewpos.height * 3 + viewpos.y,
      left: viewpos.x,
      position: 'absolute',
      'z-index': 1
    });
    return this.$el.show();
  },
  get_classid: function() {
    return this.classid;
  },
  hide: function() {
    return this.$el.hide();
  }
});

exports = exports != null ? exports : this;

exports.IsaOptionsView = IsaOptionsView;
