// Generated by CoffeeScript 1.12.5
var OWLlinkInsertView, exports;

OWLlinkInsertView = Backbone.View.extend({
  initialize: function() {
    this.render();
    return this.textarea = this.$el.find("#insert_owllink_input");
  },
  render: function() {
    var template;
    template = _.template($("#template_insertowllink").html());
    return this.$el.html(template());
  },
  events: {
    "click a#insert_owlclass": "insert_class"
  },
  get_owllink: function() {
    return this.textarea[0].value;
  },
  set_owllink: function(str) {
    return this.textarea[0].value = str;
  },
  append_owllink: function(str) {
    return this.textarea[0].value = this.textarea[0].value + str;
  },
  insert_class: function() {
    return this.append_owllink("<owl:Class IRI=\"CLASSNAME\" />");
  }
});

exports = exports != null ? exports : this;

exports.OWLlinkInsertView = OWLlinkInsertView;
