// Generated by CoffeeScript 1.12.5
var TrafficLightsView, exports;

TrafficLightsView = Backbone.View.extend({
  initialize: function() {
    return this.render();
  },
  render: function() {
    var template;
    template = _.template($("#template_trafficlight").html(), {});
    return this.$el.html(template);
  },
  events: {
    "click a#traffic_btn": "check_satisfiable"
  },
  check_satisfiable: function(event) {
    return gui.gui_instance.check_satisfiable();
  },
  turn_red: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light-red.svg");
  },
  turn_green: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light-green.svg");
  },
  turn_yellow: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light-yellow.svg");
  },
  turn_yellow_flashing: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light-red-flashing.svg");
  },
  turn_red_flashing: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light-red-flashing.svg");
  },
  turn_all: function() {
    return this.$el.find("#traffic_img").attr("src", "imgs/h-traffic-light.svg");
  }
});

exports = exports != null ? exports : this;

exports.TrafficLightsView = TrafficLightsView;
