// Generated by CoffeeScript 1.10.0
(function() {
  var css_assoc_links, css_class, css_class_unsatisfiable, css_links, exports;

  css_class = {
    '.uml-class-name-rect': {
      fill: "#ff8450",
      stroke: "#fff",
      'stroke-width': 0.5,
      filter: {
        name: 'dropShadow',
        args: {
          dx: 0.5,
          dy: 2,
          blur: 2,
          color: '#333333'
        }
      }
    },
    '.uml-class-attrs-rect': {
      fill: "#fe976a",
      stroke: "#fff",
      'stroke-width': 0.5,
      filter: {
        name: 'dropShadow',
        args: {
          dx: 0.5,
          dy: 2,
          blur: 2,
          color: '#333333'
        }
      }
    },
    '.uml-class-methods-rect': {
      fill: "#fe976a",
      stroke: "#fff",
      'stroke-width': 0.5,
      filter: {
        name: 'dropShadow',
        args: {
          dx: 0.5,
          dy: 2,
          blur: 2,
          color: '#333333'
        }
      }
    },
    '.uml-class-name-text': {
      fill: "#000"
    },
    '.uml-class-attrs-text': {
      ref: '.uml-class-attrs-rect',
      'ref-y': 0.6,
      'y-alignment': 'middle'
    },
    '.uml-class-methods-text': {
      ref: '.uml-class-methods-rect',
      'ref-y': 0.5,
      'y-alignment': 'middle',
      display: 'none'
    }
  };

  css_class_unsatisfiable = {
    '.uml-class-name-rect': {
      fill: "#f00",
      stroke: "#000",
      'stroke-width': 0.5
    },
    '.uml-class-attrs-rect': {
      fill: "#fdd",
      stroke: "#000",
      'stroke-width': 0.5
    },
    '.uml-class-methods-rect': {
      fill: "#fdd",
      stroke: "#000",
      'stroke-width': 0.5
    },
    '.uml-class-name-text': {
      fill: "#00f"
    },
    '.uml-class-attrs-text': {
      ref: '.uml-class-attrs-rect',
      'ref-y': 0.5,
      'y-alignment': 'middle'
    },
    '.uml-class-methods-text': {
      ref: '.uml-class-methods-rect',
      'ref-y': 0.5,
      'y-alignment': 'middle'
    }
  };

  css_links = {
    '.connection': {
      'stroke': '#000',
      'stroke-width': 2
    }
  };

  css_assoc_links = {
    '.connection': {
      'stroke': '#000',
      'stroke-width': 2,
      'stroke-dasharray': '5,5'
    }
  };

  exports = exports != null ? exports : this;

  exports.csstheme = {};

  exports.csstheme.css_class = css_class;

  exports.csstheme.css_class_unsatisfiable = css_class_unsatisfiable;

  exports.csstheme.css_links = css_links;

  exports.csstheme.css_assoc_links = css_assoc_links;

}).call(this);
