// Generated by CoffeeScript 1.4.0
(function() {
  var Diagrama;

    if (typeof exports !== "undefined" && exports !== null) {
    exports;

  } else {
    this;

  };

  Diagrama = (function() {

    function Diagrama() {
      this.clases = [];
      this.links = [];
    }

    Diagrama.prototype.get_clases = function() {
      return this.clases;
    };

    Diagrama.prototype.get_links = function() {
      return this.links;
    };

    Diagrama.prototype.get_clase = function(nombre) {};

    return Diagrama;

  })();

}).call(this);
