// Generated by CoffeeScript 1.4.0
(function() {
  var ERDFactory, Factory, UMLFactory, css_classes, uml;

    if (typeof exports !== "undefined" && exports !== null) {
    exports;

  } else {
    this;

  };

  uml = joint.shapes.uml;

  css_classes = {
    '.uml-class-name-rect': {
      fill: "#fff"
    },
    '.uml-class-attrs-rect': {
      fill: "#fff"
    },
    '.uml-class-methods-rect': {
      fill: "#fff"
    }
  };

  Factory = (function() {

    function Factory() {}

    Factory.prototype.create_class = function(name) {};

    return Factory;

  })();

  UMLFactory = (function() {

    function UMLFactory() {}

    UMLFactory.prototype.create_class = function(name) {
      var nueva;
      nueva = new uml.Class({
        position: {
          x: 20,
          y: 20
        },
        size: {
          width: 220,
          height: 100
        },
        name: name,
        attributes: [],
        methods: [],
        attr: css_clases
      });
      return nueva;
    };

    return UMLFactory;

  })();

  ERDFactory = (function() {

    function ERDFactory() {}

    ERDFactory.prototype.create_class = function() {};

    return ERDFactory;

  })();

  exports.Factory = Factory;

  exports.UMLFactory = UMLFactory;

  exports.ERDFactory = ERDFactory;

}).call(this);
