// Generated by CoffeeScript 1.4.0

window.onload = function() {
  var exports, graph, guiinst, newclass, newclass1, paper;
  graph = new joint.dia.Graph;
  paper = new joint.dia.Paper({
    el: $('#container'),
    width: 2000,
    height: 1000,
    model: graph,
    gridSize: 1
  });
  guiinst = new gui.GUI(graph, paper);
  gui.set_current_instance(guiinst);
  paper.on("cell:pointerclick", function(cellView, evt, x, y) {
    return guiinst.on_cell_clicked(cellView, evt, x, y);
  });
  exports = exports != null ? exports : this;
  exports.graph = graph;
  exports.paper = paper;
  exports.guiinst = guiinst;
  newclass = new Class('Person', ["dni : String", "firstname : String", "surname : String", "birthdate : Date"], []);
  newclass1 = new Class('Student', ["id : String", "enrolldate : Date"], []);
  console.log(newclass);
  guiinst.add_object_type(newclass);
  return guiinst.add_object_type(newclass1);
};
