// Generated by CoffeeScript 1.4.0
(function() {
  var CrearClaseView, crearclase, css_clase, graph, paper, uml;

    if (typeof exports !== "undefined" && exports !== null) {
    exports;

  } else {
    this;

  };

  uml = joint.shapes.uml;

  graph = new joint.dia.Graph;

  paper = new joint.dia.Paper({
    el: $('#container'),
    width: 1000,
    height: 1000,
    model: graph,
    gridSize: 1
  });

  css_clase = {
    '.uml-class-name-rect': {
      fill: "#fff"
    },
    '.uml-class-attrs-rect': {
      fill: "#fff"
    },
    '.uml-class-methods-rect': {
      fill: "#fff"
    }
  };

  CrearClaseView = Backbone.View.extend({
    initialize: function() {
      return this.render();
    },
    render: function() {
      var template;
      template = _.template($("#template_crearclase").html(), {});
      return this.$el.html(template);
    },
    events: {
      "click a#crearclase_button": "crear_clase"
    },
    crear_clase: function(event) {
      var nueva;
      alert("Creando: " + $("#crearclase_input").val() + "...");
      nueva = new uml.Class({
        position: {
          x: 20,
          y: 20
        },
        size: {
          width: 220,
          height: 100
        },
        name: $("#crearclase_input").val(),
        attributes: [],
        methods: [],
        attrs: css_clase
      });
      return graph.addCells([nueva]);
    }
  });

  crearclase = new CrearClaseView({
    el: $("#crearclase")
  });

}).call(this);
