// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    var attri, attri2, attri3, attri4, attri5, attri6, entity, entity2, exports, graph, guiinst, newattribute, newattribute2, newattribute3, newattribute4, newattribute5, newattribute6, newclass, newclass2, newlink, newlink2, newlink3, newlink4, newlink5, newlink6, paper;
    graph = new joint.dia.Graph;
    paper = new joint.dia.Paper({
      el: $('#container'),
      width: 2000,
      height: 1000,
      model: graph,
      gridSize: 1
    });
    guiinst = new gui.GUI(graph, paper);
    gui.set_current_instance(guiinst);
    guiinst.add_gui('eer', new gui.GUIEER());
    gui.gui_instance.add_gui('eer', new gui.GUIEER());
    paper.on("cell:pointerclick", function(cellView, evt, x, y) {
      return guiinst.on_cell_clicked(cellView, evt, x, y);
    });
    exports = exports != null ? exports : this;
    exports.graph = graph;
    exports.paper = paper;
    exports.guiinst = guiinst;
    newattribute = new model.eer.Attribute('dni', 'normal');
    newattribute2 = new model.eer.Attribute('firstname', 'normal');
    newattribute3 = new model.eer.Attribute('surname', 'normal');
    newattribute4 = new model.eer.Attribute('birthdate', 'normal');
    newattribute5 = new model.eer.Attribute('id', 'normal');
    newattribute6 = new model.eer.Attribute('enrolldate', 'normal');
    newclass = new model.eer.Entity('Person', [newattribute, newattribute2, newattribute3, newattribute4]);
    newclass2 = new model.eer.Entity('Student', [newattribute5, newattribute6]);
    newlink = new model.eer.LinkAttrToEntity(['Person', 'dni']);
    newlink2 = new model.eer.LinkAttrToEntity(['Person', 'firstname']);
    newlink3 = new model.eer.LinkAttrToEntity(['Person', 'surname']);
    newlink4 = new model.eer.LinkAttrToEntity(['Person', 'birthdate']);
    newlink5 = new model.eer.LinkAttrToEntity(['Student', 'id']);
    newlink6 = new model.eer.LinkAttrToEntity(['Student', 'enrolldate']);
    guiinst.add_object_type(newclass);
    guiinst.add_object_type(newclass2);
    guiinst.add_attribute(newattribute);
    guiinst.add_attribute(newattribute2);
    guiinst.add_attribute(newattribute3);
    guiinst.add_attribute(newattribute4);
    guiinst.add_attribute(newattribute5);
    guiinst.add_attribute(newattribute6);
    entity = graph.attributes.cells.models[0].id;
    entity2 = graph.attributes.cells.models[1].id;
    attri = graph.attributes.cells.models[2].id;
    attri2 = graph.attributes.cells.models[3].id;
    attri3 = graph.attributes.cells.models[4].id;
    attri4 = graph.attributes.cells.models[5].id;
    attri5 = graph.attributes.cells.models[6].id;
    attri6 = graph.attributes.cells.models[7].id;
    guiinst.add_relationship_attr(entity, attri);
    guiinst.add_relationship_attr(entity, attri2);
    guiinst.add_relationship_attr(entity, attri3);
    guiinst.add_relationship_attr(entity, attri4);
    guiinst.add_relationship_attr(entity2, attri5);
    return guiinst.add_relationship_attr(entity2, attri6);
  };

}).call(this);
