// Generated by CoffeeScript 1.4.0
(function() {
  var Product;

    if (typeof exports !== "undefined" && exports !== null) {
    exports;

  } else {
    this;

  };

  Product = (function() {

    function Product() {return ""}

    return Product;

  })();
  
  this.Product = Product;

}).call(this);
