// Generated by CoffeeScript 1.4.0
var exports, lst_clases, lst_rels, prueba, startx, starty, uml, xmax, ymax;

uml = joint.shapes.uml;

lst_clases = [];

lst_rels = [];

startx = 0;

starty = 0;

xmax = startx + 220 * 10 + 50;

ymax = starty + 100 * 10 + 50;

prueba = function(cantclases) {
  var anterior, i, xpos, ypos, _fn, _i, _results;
  xpos = startx;
  ypos = starty;
  anterior = null;
  _fn = function(i) {
    var clase, rel;
    xpos += 225;
    if (xpos >= xmax) {
      xpos = startx;
      ypos += 105;
    }
    clase = new uml.Class({
      position: {
        x: xpos,
        y: ypos
      },
      size: {
        width: 220,
        height: 100
      },
      name: 'Clase ' + String(i),
      attrs: csstheme.css_class
    });
    lst_clases.push(clase);
    if (anterior !== null) {
      rel = new uml.Generalization({
        source: {
          id: anterior.id
        },
        target: {
          id: clase.id
        }
      });
      lst_rels.push(rel);
    }
    return anterior = clase;
  };
  _results = [];
  for (i = _i = 0; 0 <= cantclases ? _i <= cantclases : _i >= cantclases; i = 0 <= cantclases ? ++_i : --_i) {
    _fn(i);
    graph.addCells(lst_clases);
    _results.push(graph.addCells(lst_rels));
  }
  return _results;
};

exports = exports != null ? exports : this;

exports.prueba = prueba;
